baseURL = "https://kmatejak.github.io/maksymiuk"

[taxonomies]
    category = 'categories'

[caches]
    [caches.images]
        dir    = ':cacheDir/galleriesdeluxe'
        maxAge = "4320h"                     # 6 months.

[params]
    [params.author]
        name        = "Anna Maksymiuk"
        email       = "kris.p@tuta.com"
        description = "Fotografia reportażowa, sesje, zdjęcia ślubne"

    [params.galleriesdeluxe]
        # One of dartsass or libsass.
        sass_transpiler = "dartsass"
        [params.galleriesdeluxe.sassvars]
            color_background = "#1d1e2c"

[params.gallerydeluxe]
    shuffle     = false
    reverse     = true
    enable_exif = false

[module]
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "content"
        target = "content"

    [[module.imports]]
        path = "github.com/kMatejak/maksymiuk"
